server:
    port: ${PRL_DOCUMENT_GENERATOR_PORT:4007}

service:
    service-auth-provider:
        health:
            context-path: /health
            uri: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://localhost:4502}${service.service-auth-provider.health.context-path}

docmosis:
    service:
        pdf-service:
            accessKey: ${DOCMOSIS_SERVICE_ACCESS_KEY:replace_me}
            renderEndpoint: "/rs/render"
            uri: ${DOCMOSIS_SERVICE_BASE_URL:http://localhost:5501}${docmosis.service.pdf-service.renderEndpoint}
            health: ${DOCMOSIS_SERVICE_BASE_URL:http://localhost:5501}/health
            devMode: ${DOCMOSIS_SERVICE_DEV_MODE_FLAG:false}

case_document_am:
    url: ${CCD_CASE_DOCS_AM_API:http://localhost:5170}

auth:
    provider:
        service:
            client:
                port: 4502
                baseUrl: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://localhost:4502}
                tokenTimeToLiveInSeconds: 900

idam:
    s2s-auth:
        microservice: ${AUTH_PROVIDER_SERVICE_CLIENT_MICROSERVICE:prl_cos_api}
        totp_secret: ${AUTH_PROVIDER_SERVICE_CLIENT_KEY:replace_me}
        url: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://localhost:4502}

http:
    connect:
        timeout: 60000
        request:
            timeout: 60000

health:
    check:
        http:
            connect:
                timeout: 5000
                request:
                    timeout: 5000

info:
    app:
        name: ${spring.application.name}

pdf:
    test:
        enabled: false

document:
    templates:
        configurationList:
            -   templateName: FL-DIV-GOR-ENG-00062.docx
                filename: TestTemplate.pdf
                document-generator: docmosis
            -   templateName: PRL-DRAFT-C100-20.docx
                filename: TestTemplate.pdf
                document-generator: docmosis
            -   templateName: PRL-C8-Final-Changes.docx
                filename: C8Document.pdf
                document-generator: docmosis
            -   templateName: PRL-C100-R1-Final-Document.docx
                filename: C100FinalDocument.pdf
                document-generator: docmosis
            -   templateName: PRL-C1A.docx
                filename: C1ADocument.pdf
                document-generator: docmosis
            -   templateName: PRL-C100-R1-Draft-Document.docx
                filename: C100DraftDocument.pdf
                document-generator: docmosis
            -   templateName: PRL-C100-R1-Draft-WelshLang.docx
                filename: C100DraftWelshDocument.pdf
                document-generator: docmosis
            -   templateName: PRL-C100-R1-Final-WelshLang.docx
                filename: C100FinalWelshDocument.pdf
                document-generator: docmosis
            -   templateName: PRL-C8-WelshLang.docx
                filename: C8WelshDocument.pdf
                document-generator: docmosis
            -   templateName: PRL-C1A-WelshLang.docx
                filename: C1AWelshDocument.pdf
                document-generator: docmosis
            -   templateName: FL401-draft.docx
                filename: Draft-DA-application.pdf
                document-generator: docmosis
            -   templateName: FL401-Final.docx
                filename: DA-application.pdf
                document-generator: docmosis
            -   templateName: PRL-DA-C8.docx
                filename: FL401C8Document.pdf
                document-generator: docmosis
            -   templateName: FL401-Final-Welsh.docx
                filename: DA-Welsh-application.pdf
                document-generator: docmosis
            -   templateName: FL401-draft-Welsh.docx
                filename: Draft-DA-Welsh-application.pdf
                document-generator: docmosis
            -   templateName: FL401-c8-welsh.docx
                filename: FL401C8WelshDocument.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDER-C21-FINAL.docx
                filename: Blank_Order_Directions_C21.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDER-C21-DRAFT-FINAL.docx
                filename: Blank_Order_Directions_C21_Draft.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDER-C21-WELSH-COMMON.docx
                filename: Blank_Order_Directions_C21_Welsh.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDER-C43A-DRAFT.docx
                filename: Special_Guardianship_Order_C43A_Draft.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDER-C43A-FINAL.docx
                filename: Special_Guardianship_Order_C43A.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDER-C43-FINAL.docx
                filename: ChildArrangements_Specific_Prohibited_Steps_C43.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDER-C43-DRAFT.docx
                filename: ChildArrangements_Specific_Prohibited_Steps_C43_Draft.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDERS-C47A-FINAL.docx
                filename: Appointment_of_a_guardian_C47A.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDERS-C47A-DRAFT.docx
                filename: Appointment_of_a_guardian_C47A_draft.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDER-C49-COMMON.docx
                filename: C49CreateOrder.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDER-C49-DRAFT-COMMON.docx
                filename: C49CreateOrderDraft.pdf
                document-generator: docmosis
            -   templateName: PRL-FL402-Notice-Of-Proceedings-Draft.docx
                filename: NoticeOfProceedings(FL402)Draft.pdf
                document-generator: docmosis
            -   templateName: PRL-FL402-Notice-Of-Proceedings-Final.docx
                filename: NoticeOfProceedings(FL402).pdf
            -   templateName: PRL-ORDERS-N117-DRAFT.docx
                filename: N117CreateOrderDraft.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDERS-N117-FINAL.docx
                filename: N117CreateOrder.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDERS-FL404-DRAFT.docx
                filename: occupation_order_FL404_draft.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDERS-FL404-FINAL.docx
                filename: occupation_order_FL404_final.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDER-FL404b-DRAFT-COMMON.docx
                filename: amended_dischared_or_varied_order_fl404b_draft.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDER-FL404b-FINAL-COMMON.docx
                filename: amended_dischared_or_varied_order_fl404b_final.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDER-C45A-FINAL.docx
                filename: Parental_Responsibility_Order_C45A.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDER-C45A-DRAFT-FINAL.docx
                filename: Parental_Responsibility_Order_C45A_draft.pdf
            -   templateName: PRL-ORDERS-FL404A-NM-DRAFT.docx
                filename: non_molestation_order_fl404a_draft.pdf
                document-generator: docmosis
            -   templateName: PRL-ORDERS-FL404A-NM-FINAL.docx
                filename: non_molestation_order_fl404a_final.pdf
                document-generator: docmosis
            -   templateName: PRL-C7-BLANK-DOCUMENT.docx
                filename: C7BlankDocument.pdf
                document-generator: docmosis
            -   templateName: PRL-C8-BLANK-DOCUMENT.docx
                filename: C8BlankDocument.pdf
                document-generator: docmosis
            -   templateName: PRL-C1A-BLANK-DOCUMENT.docx
                filename: C1ABlankDocument.pdf
                document-generator: docmosis
            -   templateName: PRL-PRIVACY-NOTICE-DOCUMENT.docx
                filename: PrivacyNoticeDocument.pdf
                document-generator: docmosis

    pdf:
        familyCourtImgKey: "familycourt"
        familyCourtImgVal: "[userImage:familycourt.png]"
        hmctsImgKey: "hmcts"
        hmctsImgVal: "[userImage:hmcts.png]"
        displayTemplateKey: "displayTemplateOnly"
        displayTemplateVal: "1"

evidence-management-api:
    service:
        stub:
            enabled: false

documentation:
    swagger:
        enabled: true

spring:
    application:
        name: "prl-dgs-api"
    web:
        resources:
            static-locations:

# GENERAL SPRING BOOT ACTUATOR CONFIG
# Context path for Spring Boot Actuator endpoints
# Allow actuator endpoints to be accessed without requiring authentication
# Enable default health indicators
# Enable disk space health check
# HEALTH ENDPOINT CONFIG
# Enable the health endpoint
# Enable sensitive health information
# Defines the URL of the health check to ${management.context-path}/health
# Caching period in milliseconds of health endpoint
# METRICS ENDPOINT CONFIG
# Enable the metrics endpoint
# Enable sensitive metrics information
management:
    endpoint:
        health:
            show-details: "ALWAYS"
            cache:
                time-to-live: 5000
    endpoints:
        web:
            base-path: /
            path-mapping:
                health: health
            exposure:
                include: info, health, metrics
    health:
      case-document-am-api:
          enabled: false

logging:
    level:
        org.springframework.web: ERROR
        uk.gov.hmcts.reform.prl.documentgenerator: DEBUG
    pattern:
        console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

azure:
  application-insights:
    instrumentation-key: ${APP_INSIGHTS_INSTRUMENTATION_KEY:00000000-0000-0000-0000-000000000000}

launchdarkly:
  sdk-key: "${LAUNCH_DARKLY_SDK_KEY:}"
