server:
    port: ${PRL_DOCUMENT_GENERATOR_PORT:4007}

service:
    service-auth-provider:
        health:
            context-path: /health
            uri: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://localhost:4502}${service.service-auth-provider.health.context-path}

docmosis:
    service:
        pdf-service:
            accessKey: ${DOCMOSIS_SERVICE_ACCESS_KEY:replace_me}
            renderEndpoint: "/rs/render"
            uri: ${DOCMOSIS_SERVICE_BASE_URL:http://localhost:5501}${docmosis.service.pdf-service.renderEndpoint}
            health: ${DOCMOSIS_SERVICE_BASE_URL:http://localhost:5501}/health
            devMode: ${DOCMOSIS_SERVICE_DEV_MODE_FLAG:false}

case_document_am:
    url: ${CCD_CASE_DOCS_AM_API:http://localhost:5170}

auth:
    provider:
        service:
            client:
                port: 4502
                baseUrl: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://localhost:4502}
                tokenTimeToLiveInSeconds: 900

idam:
    s2s-auth:
        microservice: ${AUTH_PROVIDER_SERVICE_CLIENT_MICROSERVICE:prl_dgs_api}
        totp_secret: ${AUTH_PROVIDER_SERVICE_CLIENT_KEY:replace_me}
        url: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:http://localhost:4502}

http:
    connect:
        timeout: 60000
        request:
            timeout: 60000

health:
    check:
        http:
            connect:
                timeout: 5000
                request:
                    timeout: 5000

info:
    app:
        name: ${spring.application.name}

pdf:
    test:
        enabled: false

document:
    templates:
        configurationList:
            -   templateName: FL-DIV-GOR-ENG-00062.docx
                filename: TestTemplate.pdf
                document-generator: docmosis
    pdf:
        familyCourtImgKey: "familycourt"
        familyCourtImgVal: "[userImage:familycourt.png]"
        hmctsImgKey: "hmcts"
        hmctsImgVal: "[userImage:hmcts.png]"
        displayTemplateKey: "displayTemplateOnly"
        displayTemplateVal: "1"

evidence-management-api:
    service:
        stub:
            enabled: false

documentation:
    swagger:
        enabled: true

spring:
    application:
        name: "prl-dgs-api"
    resources:
        static-locations:

# GENERAL SPRING BOOT ACTUATOR CONFIG
# Context path for Spring Boot Actuator endpoints
# Allow actuator endpoints to be accessed without requiring authentication
# Enable default health indicators
# Enable disk space health check
# HEALTH ENDPOINT CONFIG
# Enable the health endpoint
# Enable sensitive health information
# Defines the URL of the health check to ${management.context-path}/health
# Caching period in milliseconds of health endpoint
# METRICS ENDPOINT CONFIG
# Enable the metrics endpoint
# Enable sensitive metrics information
management:
    endpoint:
        health:
            show-details: "ALWAYS"
            cache:
                time-to-live: 5000
    endpoints:
        web:
            base-path: /
            path-mapping:
                health: health
            exposure:
                include: info, health, metrics
    health:
      case-document-am-api:
          enabled: true

logging:
    level:
        org.springframework.web: ERROR
        uk.gov.hmcts.reform.prl.documentgenerator: DEBUG
    pattern:
        console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

azure:
    app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:false}
